# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dec398bf082d22937ca3aee4b329125cd85dfac85ba33fdb6e0d67eb69388f62e59e8efc69890b659120bf5af90df75623d832d321ade0938352e2166857ebf3

test:
  secret_key_base: a49413ade9d478e63939438ac1a433c97e9961b28da7943a4d075ec459315f0168bb9af2c6054e7f4c4d6b619d323bcc820491c6cbbd454a0a4b219fb9ed1645

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
